/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'wsadik' at '11/24/15 12:47 AM' with Gradle 2.0
 *
 * @author wsadik, @date 11/24/15 12:47 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
